### ISSUE TITLE
glslCanvas error : Index expression must be constant

### ISSUE THREAD

**Issue by sixclones** [patriciogonzalezvivo/glslCanvas#36]
Hi,

I've found an issue when you want to dynamicly access to an index of an array.

vec2 p[9];

int i = 0;
for (float y = -1.0; y <= 1.0; y++) {
  p[i++] = y; // The error says : Index expression must be constant
}

I test this code with glslViewer and that work well.

**Comment by sixclones** [comment]
Yeah I discovered that a bit later, sorry for the useless issue.

But do you have an idea why I can't reproduce the bug on Shadertoy (https://www.shadertoy.com/view/4ttfD8) ? In other words, why it's work there and not on native webgl ?

**Comment by patriciogonzalezvivo** [comment]
I think ShaderToy is using WebGL 2.0

**Comment by sixclones** [comment]
It's a why I tought too until I try by myself with webgl2 context and that didn't change anything.
This is a kinda weird.
I close the issue, sorry for the inconvenience.
