### ISSUE TITLE
sandbox.load() isn't working

### ISSUE THREAD

**Issue by sixclones** [patriciogonzalezvivo/glslCanvas#41]
Hello,

Yesterday I wanted to try this nice tool. Following the documentation gave me a white canvas.
[Here the example](https://codepen.io/Sixclones/pen/VgVxwm?editors=1010)

Sixclones

**Comment by mikehobi** [comment]
@sixclones it looks like your codepen is not including `https://rawgit.com/patriciogonzalezvivo/glslCanvas/master/dist/GlslCanvas.js` in the codepen settings

**Comment by sixclones** [comment]
Ok that's really strange because when I created the issue, the lib was imported.
Anyway now that work, i dunno what's happened.
