### ISSUE TITLE
url broken

### ISSUE THREAD

**Issue by edap** [patriciogonzalezvivo/glslCanvas#5]
hello Patricio, the README contains a url that returns a 404
https://rawgit.com/patriciogonzalezvivo/glslCanvas/master/build/GlslCanvas.min.js
the correct one is
https://rawgit.com/patriciogonzalezvivo/glslCanvas/master/build/GlslCanvas.js

**Comment by patriciogonzalezvivo** [comment]
Fixed https://github.com/patriciogonzalezvivo/glslCanvas/commit/f9f5043740b1934827a9680dc8bd0ad77fc0407d thanks!
