### ISSUE TITLE
Is glslCanvas still supported/maintained?

### ISSUE THREAD

**Issue by digitaljohn** [patriciogonzalezvivo/glslCanvas#52]
I am wondering if this project is still maintained? I am willing to add my support/contribution if required.

John

**Comment by patriciogonzalezvivo** [comment]
Hi! I apologize for the delay keeping up PR. The book of shaders examples and glslEditor is highly tide to this project so any update need to be double check on the other two.

**Comment by digitaljohn** [comment]
Understood... when do you plan on pushing a new update to NPM?
