### ISSUE TITLE
What is the proper way to destroy glslCanvas when not used anymore?

### ISSUE THREAD

**Issue by PixelsCommander** [patriciogonzalezvivo/glslCanvas#8]
Hello Patricio

Cool thing you did with glslCanvas. Going to use it for React components and the specifics there is that components can be mounted / unmounted often. So destroying component properly without memory leak is crucial.

SInce I do not see any explicit methods for destroying glslCanvas I want to ask: What is the proper way to do this?

**Comment by patriciogonzalezvivo** [comment]
Hi thanks! I have no idea... but a quick search bring this up:
- http://stackoverflow.com/questions/23598471/how-do-i-clean-up-and-unload-a-webgl-canvas-context-from-gpu-after-use
- https://github.com/KhronosGroup/WebGLDeveloperTools/blob/master/src/debug/webgl-debug.js

I will appreciate any PR concerning this issue : )

**Comment by patriciogonzalezvivo** [comment]
Wait! I did ad this: https://github.com/patriciogonzalezvivo/glslCanvas/blob/master/src/GlslCanvas.js#L166-L180

It will delete textures and shader program... but I'm uncertain if it's the best way to delete the WebGL context. Suddenly `= null ` doesn't seems very elegant : )

**Comment by PixelsCommander** [comment]
This is a proper way to clean objects in JS =) There is a delete keyword but it have weird behavior. Cool thanks. Will try this and make PR if there is a potential improvement.

**Comment by patriciogonzalezvivo** [comment]
thanks! I'm curious to see what you build with it. : )

**Comment by cmalven** [comment]
This doesn't work for me when using a texture. I receive the following error javascript error:

```
Uncaught TypeError: Failed to execute 'deleteTexture' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLTexture'.
    at GlslCanvas.destroy (mixin.js:56)
```
